import type { Conversation, Agent, Message } from '../types';

export const mockAgent: Agent = {
  id: '1',
  name: 'Sarah Johnson',
  email: 'sarah@livechat.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
  status: 'online',
};

export const mockMessages: Message[] = [
  {
    id: '1',
    content: 'Hi! How can I help you today?',
    timestamp: new Date(Date.now() - 300000),
    senderType: 'agent',
    senderName: 'Sarah Johnson',
    senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    status: 'read',
  },
  {
    id: '2',
    content: 'I need help with the pricing plans. Which one would be best for a small team of 5 people?',
    timestamp: new Date(Date.now() - 240000),
    senderType: 'visitor',
    senderName: 'John Doe',
    status: 'read',
  },
  {
    id: '3',
    content: 'I\'d recommend our Team plan. It includes all essential features and supports up to 10 agents. Would you like me to send you more details?',
    timestamp: new Date(Date.now() - 180000),
    senderType: 'agent',
    senderName: 'Sarah Johnson',
    senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    status: 'read',
  },
  {
    id: '4',
    content: 'Yes please! Also, do you offer any trial period?',
    timestamp: new Date(Date.now() - 120000),
    senderType: 'visitor',
    senderName: 'John Doe',
    status: 'read',
  },
];

export const mockConversations: Conversation[] = [
  {
    id: '1',
    visitor: {
      id: 'v1',
      name: 'John Doe',
      email: 'john@example.com',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
      location: 'New York, US',
      browser: 'Chrome 120',
      os: 'Windows 11',
      currentPage: '/pricing',
      localTime: '10:45 AM',
    },
    lastMessage: 'Yes please! Also, do you offer any trial period?',
    lastMessageTime: new Date(Date.now() - 120000),
    unreadCount: 0,
    status: 'active',
    messages: mockMessages,
    tags: ['Sales', 'VIP'],
    notes: 'VIP customer, interested in Team plan',
  },
  {
    id: '2',
    visitor: {
      id: 'v2',
      name: 'Sarah Kim',
      email: 'sarah.k@company.com',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SarahK',
      location: 'San Francisco, US',
      browser: 'Safari 17',
      os: 'macOS 14',
      currentPage: '/features',
      localTime: '7:45 AM',
    },
    lastMessage: 'Thanks for the help! That solved my issue.',
    lastMessageTime: new Date(Date.now() - 300000),
    unreadCount: 0,
    status: 'resolved',
    messages: [],
    tags: ['Support'],
  },
  {
    id: '3',
    visitor: {
      id: 'v3',
      name: 'Mike Chen',
      email: 'mike@startup.io',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
      location: 'Austin, US',
      browser: 'Firefox 121',
      os: 'Ubuntu 22.04',
      currentPage: '/integrations',
      localTime: '9:45 AM',
    },
    lastMessage: 'Can you help me with API integration?',
    lastMessageTime: new Date(Date.now() - 180000),
    unreadCount: 2,
    status: 'active',
    messages: [],
    tags: ['Technical'],
  },
  {
    id: '4',
    visitor: {
      id: 'v4',
      name: 'Emily White',
      email: 'emily@agency.com',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
      location: 'London, UK',
      browser: 'Edge 120',
      os: 'Windows 10',
      currentPage: '/contact',
      localTime: '3:45 PM',
    },
    lastMessage: 'I\'d like to schedule a demo',
    lastMessageTime: new Date(Date.now() - 600000),
    unreadCount: 1,
    status: 'queued',
    messages: [],
    tags: ['Demo'],
  },
  {
    id: '5',
    visitor: {
      id: 'v5',
      name: 'David Brown',
      email: 'david@enterprise.com',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
      location: 'Toronto, CA',
      browser: 'Chrome 120',
      os: 'macOS 13',
      currentPage: '/enterprise',
      localTime: '10:45 AM',
    },
    lastMessage: 'What are the enterprise features?',
    lastMessageTime: new Date(Date.now() - 900000),
    unreadCount: 0,
    status: 'active',
    messages: [],
    tags: ['Enterprise', 'Sales'],
  },
];
